version: "2.4"
services:

  wrk:
    build: ../wrk
    depends_on:
      api:
        condition: service_healthy

  api:
    build: .
    environment:
      NODE_ENV: "production"
      DEBUG: "*"
      PORT: "8080"
      DB_URI: "mongodb://db:27017/test"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
